### ISSUE TITLE
Installed questions

### ISSUE THREAD

**Issue by yuyadanyadan** [swansonk14/SyntheMol#10]
Thanks for your sharing! When I'm installing the packages, I'm always in trouble.
Is it because we don't have access to download these packages in China?

ERROR: Could not find a version that satisfies the requirement chemfunc==1.0.3 (from versions: none)
ERROR: No matching distribution found for chemfunc==1.0.3

or 
ERROR: Could not find a version that satisfies the requirement synthemol (from versions: none)
ERROR: No matching distribution found for synthemol

**Comment by swansonk14** [comment]
I'm going to close this issue, but please reopen it if you're still having problems!
