### ISSUE TITLE
reaction_to_building_blocks.pkl

### ISSUE THREAD

**Issue by jinzhezhang** [swansonk14/SyntheMol#20]
Dear Authors,

Sorry the question might seems to be a bit trivial. 

I am having a bit trouble creating reaction_to_building_blocks.pkl file for a customized smiles dataset. From my understanding, it should be a dictionary where `dict[reaction_id][reactant_index]` is a set of building block smiles which matches `reactions[reaction_id][reactant_index].query_mol` . However, during the debugging, my customized pkl files failed to run. During my debugging process, I tested the given reaction_to_building_blocks.pkl in the repo against the smarts provided in the reaction using the following snippet, it seems that the bb smiles in this pkl file often don't match with the smarts of the 13 REAL reactions. Am I making some mistakes? 

```
from rdkit import Chem
import pickle as pkl
import sys
sys.path.append('/home/jzhang/SyntheMol/synthemol')
from reactions.real import REAL_REACTIONS
pkl_1 = '/home/jzhang/SyntheMol/synthemol/resources/real/reaction_to_building_blocks.pkl'
with open(pkl_1, 'rb') as f:
    real = pkl.load(f)

for reaction in REAL_REACTIONS:
    reaction_id = reaction.id
    print(reaction_id)
    for reactant_idx in range(len(real[reaction_id].keys())):
        res = 0
        total = len(real[reaction_id][reactant_idx])
        for smiles in real[reaction_id][reactant_idx]:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                raise ValueError(f'Invalid SMILES: {smiles}')
            res += mol.HasSubstructMatch(reaction.reactants[reactant_idx].query_mol)
        print(reaction_id, reactant_idx, res, total)

```
The output is:

> 275592
> 275592 0 0 1488
> 275592 1 16146 16146
> 275592 2 20040 20040
> 22
> 22 0 0 43793
> 22 1 26268 26268
> 11
> 11 0 0 25891
> 11 1 14411 14411
> 527
> 527 0 0 29518
> 527 1 16522 16522
> 240690
> 240690 0 0 41412
> 240690 1 23369 23369
> 2430
> 2430 0 0 5880
> 2430 1 0 26436
> 2708
> 2708 0 0 10272
> 2708 1 0 13771
> 2230
> 2230 0 0 15636
> 2230 1 6236 6236
> 2718
> 2718 0 0 15460
> 2718 1 0 5221
> 40
> 40 0 0 29010
> 40 1 3061 3061
> 27
> 27 0 0 26115
> 27 1 3702 3702
> 271948
> 271948 0 0 9052
> 271948 1 0 9182
> 1458
> 1458 0 19157 19157
> 1458 1 5814 5814

This results suggests that building blocks saved in reaction_to_building_blocks.pkl doesn't match the smarts that it suppose to be able to match. For example, reaction 275592's reactants[0] have 1488 smiles under REAL_REACTIONS[0][0] ([0][0] instead of [275592][0] because it's a list) matches the smarts `CC(C)(C)OC(=O)[N:1]([*:2])[*:3].[*:4][N:5]([H])[*:6]`. reactants[1] and reactants[2] have fully matched with all bb smiles. 
> 275592 0 0 1488
> 275592 1 16146 16146
> 275592 2 20040 20040

Also, in Supplementary Data 8 (SD8. Generated), for example line 88, 123, 143, 175. The generated reagent_1_1 doesn't seem to match the smarts of reactants[0] `CC(C)(C)OC(=O)[N:1]([*:2])[*:3].[*:4][N:5]([H])[*:6]`, but reagent_1_2 and reagent_1_3 matches reactants[1] and reactants[2] respectively. 

<img width="1740" alt="image" src="https://github.com/user-attachments/assets/b371408e-792f-4542-b545-7566c900e43b">

**Comment by jinzhezhang** [comment]
Quick update here:
I found the reason of this inconsistency, it's due to AddHs function in utls.convert_to_mol(). The pattern is not the same adding or not hydrogen in the building blocks and therefore caused this inconsistency. After adding hydrogen into the BBs, we can now reproduce the results. 

I will close this issue as it's fixed. Thanks!

**Comment by swansonk14** [comment]
Hi @jinzhezhang,

Thanks for raising the issue and I'm glad you were able to resolve it! Please let me know if you run into any other issues!

Best,
Kyle

**Comment by jinzhezhang** [comment]
Thank you! Just want to quickly confirm, by running the same program twice, is it normal that the results (at least for the first few rollouts) are completely identical (meaning no stochastic)?

**Comment by swansonk14** [comment]
Hi @jinzhezhang,

I realize the random seed is a bit confusing because by default, it actually doesn't have an effect. By default, at every step in a rollout, SyntheMol considers all possible building blocks and chooses the best one. If you set `num_expand_nodes` to be a number (and not the default of `None`), then SyntheMol will randomly select that many building blocks at each step and then choose the best building block from among those. The random seed only affects this selection process. So if you keep `num_expand_nodes=None` as is the default, then the random seed will not have an effect.

Best,
Kyle
